package com.prafullkumar.workout.domain.model

enum class BodyPart(val displayName: String) {
    CHEST("Chest"),
    UPPER_CHEST("Upper Chest"),
    LOWER_CHEST("Lower Chest"),
    BACK("Back"),
    LATS("Lats"),
    TRAPS("Traps"),
    SHOULDERS("Shoulders"),
    FRONT_DELTS("Front Delts"),
    SIDE_DELTS("Side Delts"),
    REAR_DELTS("Rear Delts"),
    BICEPS("Biceps"),
    TRICEPS("Triceps"),
    FOREARMS("Forearms"),
    CORE("Core"),
    ABS("Abs"),
    OBLIQUES("Obliques"),
    LOWER_BACK("Lower Back"),
    GLUTES("Glutes"),
    QUADS("Quads"),
    HAMSTRINGS("Hamstrings"),
    CALVES("Calves"),
    LOWER_BODY("Lower Body"),
    ERECTOR_SPINAE("Erector Spinae"),
    RHOMBOIDS("Rhomboids"),
    UPPER_BACK("Upper Back"),
    ARMS("Arms"),
}
